version: "3.7"

services:
  php:
    image: php:7.2-fpm
    volumes:
      - ./php:/var/www/myapp
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
      - /gt/sc-prog-repos/ptfile/:/gt/sc-prog-repos/ptfile/
    ports:
      - 4000:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
