version: "3"
services:
  puppet:
    container_name: puppet
    build:
      context: .
    environment:
      - VNC_RESOLUTION=1440x900
    user: "0"
    ipc: host
    restart: always
    working_dir: /gt/sc-prog-repos/ptfile/puppet
    command: "/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"
    ports:
      - 5901:5901
    volumes:
      - /gt/sc-prog-repos/ptfile/.github/docker/puppet/etc-supervisor-conf.d-services.conf:/etc/supervisor/conf.d/services.conf
      - /gt/sc-prog-repos/ptfile/:/gt/sc-prog-repos/ptfile/
