version: "3"
services:
  ptclient:
    image: node:14.1.0
    ipc: host
    tty: true
    ports:
      - 80:80
    working_dir: /gt/sc-prog-repos/ptfile/ptclient
    command: bash -c "npm install && npm run build && npm run start-nuxt-in-test-env"
    depends_on:
      - ptserver
    volumes:
      - /gt/sc-prog-repos/ptfile/ptclient:/gt/sc-prog-repos/ptfile/ptclient # This will allow hot reloading when files are changed on host

  ptserver:
    image: node:14.1.0
    ipc: host
    tty: true
    ports:
      - 8000:8000
    working_dir: /gt/sc-prog-repos/ptfile/ptserver
    command: bash -c "npm install && npm run start-test"
    depends_on:
      - mariadb
    volumes:
      - /gt/sc-prog-repos/ptfile/:/gt/sc-prog-repos/ptfile/ # This allows file changes on host to be available inside docker container without recreating docker image.
      # For reasons of this volume mount see the vue: section comments
  mariadb:
    image: mariadb:10.4
    ipc: host
    restart: always
    volumes:
      - /tmp/var/lib/mysql:/var/lib/mysql
      - /gt/sc-prog-repos/ptfile/:/gt/sc-prog-repos/ptfile/
    ports:
      - 4000:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # For rules regarding mysql pass read https://hub.docker.com/_/mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
