# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Patient file CI # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#name

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ptclient-app: # This is the first job https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
    runs-on: ubuntu-18.04 # For the list of github hosted runners see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
      # Downloads a copy of the code before running CI tests Ref: https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
      - name: Check out repository code
        uses: actions/checkout@v2 # This is bringing source code to ubuntu server defined in line 13 Localtion of checkout is /home/runner/work/ptfile/ptfile

      - name: Move coce to expected folder
        run: |
          sudo mkdir -p /gt/sc-prog-repos
          sudo mv /home/runner/work/ptfile/ptfile /gt/sc-prog-repos

      - name: Getting env info - 1
        run: |
          ls
          pwd
          docker ps -a

      - name: start ptserver ptclient and mariadb
        run: |
          cd /gt/sc-prog-repos/ptfile/utils/prod-setup
          docker-compose up -d
          docker-compose -f maria-10.4-docker-compose.yml up -d

      - name: Getting env info - 2
        run: |
          ls
          pwd
          docker ps -a
          cd /gt/sc-prog-repos/ptfile/utils/prod-setup
          docker-compose logs -f

      - name: run-tests
        run: |
          wget www.google.com

#
#
#
#
# Q1) What is the tree structure?
# The tree strcuture is
#  -- Workflow (Made up of 1 or more jobs)
#    -- Jobs (Jobs run in parallel by default. Each job runs in a fresh version of the virtual environment)
#       -- Services
#       -- Steps # Job contains a sequence of tasks called steps https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
#          -- name
#          -- uses
#          -- run
#
#
#
#
# Q2) Why have 3 services and not 3 jobs?
# The 3 docker containers are not run as 3 different jobs.
# A. Since ptserver job needs mysql server job to stay on. But mysql-server is not waiting for ptserver
# Future RnD:
# https://github.community/t/keep-jobs-services-alive/118912
# https://github.community/t/mariadb-mysql-service-is-unealthy/17390
# B. When run as 3 services each can ping the other with the hostname of the service given by docker.
#
#
#
#
# Q3) How to get source code inside ptserver and ptclient images?
# Option1: On github I can create a custom docker image at each commit and then inside build.yml I can say:
# ptserver:
#  image: ptserver-node:14 Ref: https://www.learncloudnative.com/blog/2020-02-20-github-action-build-push-docker-images/
#
# Option 2:
# volume mount for e.g at:
# https://github.community/t/keep-jobs-services-alive/118912
# https://github.community/t/custom-docker-action-mounted-volumes/17013
#
# Preferred: Option 2
